### ISSUE TITLE
Is ReverseDiff 0.7 compatible?

### ISSUE THREAD

**Issue by xukai92** [JuliaDiff/ReverseDiff.jl#109]

**Comment by jrevels** [comment]
ReverseDiff isn't actively developed anymore now that there are so many similar AD packages and I'm trying to work on some next-gen stuff, but I can probably at least update it for v0.7/1.0 so people can keep using it until Capstan is ready. I'll try to get to it by next week sometime.

In the meantime, one could try Nabla.jl, AutoGrad.jl, Flux.jl, or XGrad.jl.

**Comment by baggepinnen** [comment]
That would be great! ReverseDiff is the only package I have gotten to work with my seemingly exotic nested differentiation use case. (ReverseDiff(ForwardDiff) mixed)

**Comment by axsk** [comment]
It also breaks (probably not the only problem though) Klara.jl
c.f. https://github.com/JuliaStats/Klara.jl/issues/174

**Comment by jrevels** [comment]
I have a branch that's passing tests on v0.7 now with only a few deprecation warnings left to tackle, but they'll require some work (the `A_mul_B` deprecations). I also have not yet updated to the new broadcast machinery, and expect it to be nontrivial. 

Won't have a lot of time to work on it in the next few days, but hopefully will be able to get a PR in at the end of the week.
