### ISSUE TITLE
Differentiating a vector-input function

### ISSUE THREAD

**Issue by niclasbrok** [JuliaDiff/ReverseDiff.jl#113]
I'm currently doing some tests with this package and found something weird - when I define the functions:

```
function f(x)
return sum([5 * x[1]; 10 * x[2]])
end
```

```
function g(x)
    out = zeros(2)
    out[1] = 5 * x[1]
    out[2] = 10 * x[2]
    return sum(out)
end
```

I find that the function `ReverseDiff.gradient` doesn't work for `g` - for the test vector `x0 = [10; 15]` I get that `ReverseDiff.gradient(g, x0)` yields a zero vector (`[0; 0]`) while `ReverseDiff.gradient(f, x0)` yields `[5; 10]` (as expected).

Any explanation for this? Am I missing something?

**Comment by jrevels** [comment]
Thanks for filing the issue!

This is actually the same as https://github.com/JuliaDiff/ReverseDiff.jl/issues/76 (see also https://github.com/JuliaDiff/ReverseDiff.jl/pull/90); closing as a duplicate.

If this is a problem you're hitting in real-world code, it should be fixable by changing `zeros(2)` to `fill!(similar(x), zero(eltype(x)))`.
