### ISSUE TITLE
Array of Structs -> Struct of Array conversion

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiff/ReverseDiff.jl#130]
I am not quite sure how to do it here. I think @mohamed82008 mentioned it once.

**Comment by mohamed82008** [comment]
Can you give an example of the desired behavior comparing it to the current one? Note that `ReverseDiff.TrackedReal` is more complicated than `ForwardDiff.Dual`. `TrackedReal` holds a reference to the `TrackedArray` it may have come from.

**Comment by ChrisRackauckas** [comment]
When `x` is a tracked array I want to do things like:

```julia
[x[1] + x[2],exp(x[2])]
```

and then re-collect it back to a TrackedArray. `Tracker.collect` worked in these scenarios but I haven't found the right alternative in here.

**Comment by ChrisRackauckas** [comment]
With https://github.com/JuliaDiff/ReverseDiff.jl/pull/125, this is fixed by doing `reduce(vcat,x)`
