### ISSUE TITLE
Package author(s) for citation 

### ISSUE THREAD

**Issue by ctkelley** [JuliaDiff/ReverseDiff.jl#136]
Hi, I want to cite this package in a book and can't figure out the author field. So far I'm using

@misc{reverseDiff,
title="{ReverseDiff.jl}",
year=2020,
note="Julia Package",
howpublished="https://github.com/JuliaDiff/ReverseDiff.jl"
}

which works well with the publisher's LaTeX style. So .... author = ?
Thanks,

-- Tim

**Comment by mohamed82008** [comment]
The author is @jrevels.

**Comment by ctkelley** [comment]
Thanks.

C. T. Kelley
Mathematics Department
NCSU
tim_kelley@ncsu.edu
