### ISSUE TITLE
Problem with getindex for ReverseDiff.TrackedArray if Integer is a UInt16

### ISSUE THREAD

**Issue by mjohnson541** [JuliaDiff/ReverseDiff.jl#139]
Started getting this error after updating from 1.2.0 to 1.4.1:  

MethodError: no method matching ReverseDiff.TrackedArray(::Float64, ::Float64, ::Array{ReverseDiff.AbstractInstruction,1})
Closest candidates are:
  ReverseDiff.TrackedArray(!Matched::AbstractArray{V,N}, !Matched::AbstractArray{D,N}, ::Array{ReverseDiff.AbstractInstruction,1}) where {V, D, N} at ~/.julia/packages/ReverseDiff/tCOFA/src/tracked.jl:86

Stacktrace:
 [1] getindex(::ReverseDiff.TrackedArray{Float64,Float64,1,Array{Float64,1},Array{Float64,1}}, ::UInt16) at ~/.julia/packages/ReverseDiff/tCOFA/src/tracked.jl:337

When the indexes are changed to Int64 no error is thrown.

**Comment by amartinhuertas** [comment]
Hi everyone, 

does anyone know if this issue was ever addressed? 

Thanks!
@amartinhuertas

**Comment by kishore-nori** [comment]
We encounter a similar error when the there there is a `getindex` call on `ReverseDiff.TrackedArray` using `Int32`. Following is the error:
```julia
ERROR: MethodError: no method matching ReverseDiff.TrackedArray(::Float64, ::Float64, ::Vector{ReverseDiff.AbstractInstruction})
Closest candidates are:
 ReverseDiff.TrackedArray(::AbstractArray{V, N}, ::AbstractArray{D, N}, ::Vector{ReverseDiff.AbstractInstruction}) where {V, D, N} at ~/.julia/packages/ReverseDiff/c21a6/src/tracked.jl:83
Stacktrace:
  [1] getindex(t::ReverseDiff.TrackedArray{Float64, Float64, 1, Vector{Float64}, Vector{Float64}}, _inds::Int32)
```

Will try to come up with an MWE!
