### ISSUE TITLE
Need an `increment_deriv!` overload for `Array{TrackedReal}`

### ISSUE THREAD

**Issue by Libbum** [JuliaDiff/ReverseDiff.jl#159]
Follow-up from this [discourse thread](https://discourse.julialang.org/t/correct-sensealg-for-an-ensemble-problem-of-stochastic-uodes-with-diagonal-noise/50490?u=libbum), a recent addition to SciML/DiffEqNoiseProcess.jl#75 expects to be able to handle `increment_deriv!(::ReverseDiff.TrackedReal{Float32,Float32,ReverseDiff.TrackedArray{Float32,Float32,1,Array{Float32,1},Array{Float32,1}}}, ::Array{Float64,1})` (at least for the MWE listed at the bottom of the discourse post).

I took a quick look into the implementation of `increment_deriv!`, but I'm not familiar enough with the codebase to start a PR unfortunately. Seems like `Array{TrackedReal}` might be better to be parsed to a `TrackedArray` back on the DiffEqNoiseProcess side? \*shrugs\* Would be happy to assist on a solution with some guidance from maintainers here.

**Comment by ChrisRackauckas** [comment]
This is the overload you need: https://github.com/SciML/DiffEqNoiseProcess.jl/pull/75 2 . But now I’m going to punt it over to @mohamed82008 since it’s erroring because the output of the function is an Array{TrackedReal} so it can’t increment_deriv!, and reduce(vcat,output) isn’t giving a TrackedArray.

**Comment by mohamed82008** [comment]
`reduce(vcat, vec)` gives a TrackedArray
```julia
julia> using ReverseDiff

julia> ReverseDiff.track.(rand(4))
4-element Array{ReverseDiff.TrackedReal{Float64,Float64,Nothing},1}:
 TrackedReal<7ez>(0.695715967578153, 0.0, J5y, ---)
 TrackedReal<6UC>(0.2056547800242703, 0.0, Bmm, ---)
 TrackedReal<5O4>(0.0838819932410435, 0.0, LZV, ---)
 TrackedReal<INN>(0.3284156614508331, 0.0, 3BL, ---)

julia> reduce(vcat, ReverseDiff.track.(rand(4)))
4-element ReverseDiff.TrackedArray{Float64,Float64,1,Array{Float64,1},Array{Float64,1}}:
 TrackedReal<9Oi>(0.6457446789045893, 0.0, Ero, 1, ENV)
 TrackedReal<4ek>(0.7665688199563245, 0.0, Ero, 2, ENV)
 TrackedReal<ApP>(0.5386739593143226, 0.0, Ero, 3, ENV)
 TrackedReal<K9I>(0.10983069012205471, 0.0, Ero, 4, ENV)
```

**Comment by mohamed82008** [comment]
>(::ReverseDiff.TrackedReal{Float32,Float32,ReverseDiff.TrackedArray{Float32,Float32,1,Array{Float32,1},Array{Float32,1}}}, ::Array{Float64,1})

There seems to be a mixing of `Float32` and `Float64` here. Is that intentional?

**Comment by ChrisRackauckas** [comment]
Oh interesting. That could lead to the issue.  `α = initial_params(ann)` is `Float32`, so given the model he is using, he might want to do `α = Float64.(initial_params(ann))`

**Comment by mohamed82008** [comment]
I am trying to re-run the example to figure out what's going on. Precompiling....

**Comment by mohamed82008** [comment]
The following seems to be using Zygote not ReverseDiff!

```julia
using Plots, DiffEqFlux, Flux, Optim, LinearAlgebra, DifferentialEquations, ReverseDiff
using Statistics
using DiffEqSensitivity
using DifferentialEquations.EnsembleAnalysis

function sys!(du, u, p, t)
    r, e, μ, h, ph, z, i = p
    du[1] = e * 0.5 * (5μ - u[1]) # nutrient input time series
    du[2] = e * 0.05 * (10μ - u[2]) # grazer density time series
    du[3] = 0.2 * exp(u[1]) - 0.05 * u[3] - r * u[3] / (h + u[3]) * u[4] # nutrient concentration
    du[4] =
        r * u[3] / (h + u[3]) * u[4] - 0.1 * u[4] -
        0.02 * u[4]^z / (ph^z + u[4]^z) * exp(u[2] / 2.0) + i #Algae density
end

function noise!(du, u, p, t)
    du[1] = p[end] # n
    du[2] = p[end] # n
    du[3] = 0.0
    du[4] = 0.0
end


# I've dropped the time frame down quite a bit here just to try to get it to run.
#datasize = 30
#tspan = (0.0f0, 10.0f0)
datasize = 4
tspan = (0.0f0, 3.0f0)
tsteps = range(tspan[1], tspan[2], length = datasize)
u0 = Float32[1.0, 1.0, 1.0, 1.0]

p_ = Float32[1.1, 1.0, 0.0, 2.0, 1.0, 1.0, 1e-6, 1.0]

prob = SDEProblem(sys!, noise!, u0, tspan, p_)
ensembleprob = EnsembleProblem(prob)

solution = solve(
    ensembleprob,
    EnsembleThreads();
    trajectories = 10,
    abstol = 1e-5,
    reltol = 1e-5,
    maxiters = 1e8,
    saveat = tsteps,
)

(truemean, truevar) = Array.(timeseries_steps_meanvar(solution))

# Generate a NN with four inputs [L, G, N, A] and two outputs [NN1, NN2]
ann = FastChain(FastDense(4, 32, tanh), FastDense(32, 32, tanh), FastDense(32, 2))
α = initial_params(ann)

function dudt_(du, u, p, t)
    r, e, μ, h, ph, z, i = p_

    # we replace each of our MM values with the result of the NN.
    MM = ann(u, p)

    du[1] = e * 0.5 * (5μ - u[1]) # nutrient input time series
    du[2] = e * 0.05 * (10μ - u[2]) # grazer density time series
    du[3] = 0.2 * exp(u[1]) - 0.05 * u[3] - MM[1] # nutrient concentration
    du[4] = MM[2] - 0.1 * u[4] - 0.02 * u[4]^z / (ph^z + u[4]^z) * exp(u[2] / 2.0) + i #Algae density
end
function noise_(du, u, p, t)
    du[1] = p_[end]
    du[2] = p_[end]
    du[3] = 0.0
    du[4] = 0.0
end

prob_nn = SDEProblem(dudt_, noise_, u0, tspan, p = nothing)

function loss(θ)
    tmp_prob = remake(prob_nn, p = θ)
    ensembleprob = EnsembleProblem(tmp_prob)
    tmp_sol = solve(
        ensembleprob,
        EnsembleThreads();
        saveat = tsteps,
        trajectories = 2, # Drop down a little for troubleshooting
        sensealg = ReverseDiffAdjoint(),
    #    sensealg = ForwardDiffSensitivity(),
    )
    (tmp_mean, tmp_var) = Array.(timeseries_steps_meanvar(tmp_sol))
    sum(abs2, truemean - tmp_mean) + 0.1 * sum(abs2, truevar - tmp_var), tmp_mean
end

# Test
loss(α) # @btime 360 ms

const losses = []

callback(θ, l, pred) = begin
    push!(losses, l)
    println("Current loss after $(length(losses)) iterations: $(losses[end])")
    false
end

res1 = DiffEqFlux.sciml_train(
    loss,
    α,
    ADAM(0.1),
    cb = callback,
    maxiters = 200,
   # allow_f_increases = true,
)
```

**Comment by mohamed82008** [comment]
I am getting Zygote mutation errors here coming from `DiffEqBase.timeseries_steps_meanvar`. Please post a link to the toml files here and try re-producing the error using the above code or any variation of it.

**Comment by ChrisRackauckas** [comment]
I thought I mentioned that in discourse already. That function mutates so you can't use it in a loss function, but that's a different issue. I think @Libbum added a version of the loss function that didn't use it.

**Comment by mohamed82008** [comment]
Ah found it. Let me try.

**Comment by Libbum** [comment]
Yeah, sorry. The mutation issue is fixed in the example at the bottom of the thread. Mixing Float64 and Float32 is essentially my laziness just trying to get the code working first, whichever way we need to go on that is fine.

**Comment by mohamed82008** [comment]
Ya I think it's a problem in DiffEqSensitivities. The adjoint is called with an input array of arrays.

**Comment by mohamed82008** [comment]
This seems to be causes by the fact that the output of `solve` here is an array of arrays.

**Comment by ChrisRackauckas** [comment]
That's always the case, and it's usually fine? What's the full current code that demonstrates the issue?

**Comment by mohamed82008** [comment]
For SDEs, the `sol.u` is an array of arrays. But the forward-pass function in the ReverseDiff concrete_solve_adjoint returns `Array(sol)` which is a matrix. This seems to be causing confusion where the `ybar` is an array of arrays but the `output` is a matrix.

**Comment by mohamed82008** [comment]
An if statement and a loop fixed it. But I am running tests.

**Comment by mohamed82008** [comment]
@Libbum please try the DiffEqSensitivity PR.

**Comment by mohamed82008** [comment]
Closing since this isn't a ReverseDiff issue per se.
