### ISSUE TITLE
Segfaults in Julia 1.7.0-beta3.0 on mac

### ISSUE THREAD

**Issue by ksil** [JuliaDiff/ReverseDiff.jl#182]
I'm on Mac OS 10.14.6 and downloaded the Julia 1.7.0-beta3.0 binary online (release-1.7/e76c9dad42). ReverseDiff was installed the standard way via the package manager. Very simple ReverseDiff commands are resulting in segfaults and Julia crashing. For example,
```
ReverseDiff.gradient(x -> dot(x, x), ones(5))
```
and
```
cfg = ReverseDiff.GradientConfig(zeros(5))
```
both result in segfaults.

I do not have this problem on Julia 1.6.1, but another user (https://github.com/ksil/LFPSQP.jl/issues/1) reported the problem on Julia 1.6.2 as well.

**Comment by devmotion** [comment]
Does it still crash? We test ReverseDiff with Julia 1.7.0 successfully (e.g. https://github.com/JuliaDiff/ReverseDiff.jl/runs/4550524617?check_suite_focus=true) but only on Ubuntu.

**Comment by ksil** [comment]
Everything seems to be fine on Julia 1.7.1, so probably fine to close this issue!

(Interestingly, ReverseDiff v1.10.0 still crashes on Julia 1.7.0-beta3.0, so I'm not sure what the issue is with that Julia version...)
