### ISSUE TITLE
broken link to doc

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaDiff/ReverseDiff.jl#260]
trying [docs stable](https://juliadiff.org/ReverseDiff.jl/stable)

gives an error

**Comment by devmotion** [comment]
This is a known CI issue which unfortunately is not resolved yet, see eg  https://github.com/JuliaDiff/ReverseDiff.jl/pull/255#issue-2246604116 As a workaround you can use the dev version of the docs.
