### ISSUE TITLE
More in depth examples

### ISSUE THREAD

**Issue by domluna** [JuliaDiff/ReverseDiff.jl#27]
Hi Jared,

Awesome project here! I do think it's lacking a bit in the example realm. The `gradient.jl` example is nice, shows the API and what not, but, I'm still not sure how it fits in a more complicated example. 

Maybe a neural net training on MNIST would be a good starting point. I've tried to do this myself but ran into some issues.

https://github.com/HIPS/autograd/tree/master/examples has a bunch of good ones.

**Comment by jrevels** [comment]
Thanks for the kind words!

> Maybe a neural net training on MNIST would be a good starting point. 

I was actually planning on adding this within the next week or so. Stay tuned!

**Comment by domluna** [comment]
Awesome, looking forward to it!

**Comment by mohamed82008** [comment]
Closing this because it is out of scope. Please check Flux.
