### ISSUE TITLE
Replace Array{TapeReal} with TapeArray

### ISSUE THREAD

**Issue by jmxpearson** [JuliaDiff/ReverseDiff.jl#3]
We want this so that custom Array types that don't subtype AbstractArray can work. Also, arrays of distributions with TapeReal parameters. 

Possible API: `wrap` and `unwrap` to convert Arrays of TapeReals to TapeArrays and vice-versa.

**Comment by jrevels** [comment]
Closing since `TrackedArrays` now exist.
