### ISSUE TITLE
(Example for) result of type DiffBase.GradientResult

### ISSUE THREAD

**Issue by scidom** [JuliaDiff/ReverseDiff.jl#61]
If not mistaken, the function `gradient!(result, f, input)` accepts a `result` input argument of type `Tuple{Array{Float64,2},Array{Float64,2}}`. Is it also possible to accept a `result` input argument of type `DiffBase.GradientResult`, in a way that ForwardDiff does?

I checked the documentation, where it seems that `result` can be of type `DiffBase.DiffResult`, and wasn't sure what is the relation between `DiffBase.DiffResult` and `DiffBase.GradientResult`.

Moreover, would it be possible to provide a simple example of calling `gradient!()` using a `result` of type `DiffBase.GradientResult` or `DiffBase.DiffResult`?

**Comment by jrevels** [comment]
`DiffResult` is a type, `GradientResult` is a constructor for that type. So this is already supported, from the docs (which I guess you've seen from your comment, but just for any onlookers):

```julia
help?> ReverseDiff.gradient!
  ReverseDiff.gradient!(result, f, input, cfg::GradientConfig = GradientConfig(input))

  Returns result. This method is exactly like ReverseDiff.gradient(f, input, cfg), except it stores the resulting
  gradient(s) in result rather than allocating new memory.

  result can be an AbstractArray or a Tuple of AbstractArrays. The result (or any of its elements, if isa(result,
  Tuple)), can also be a DiffBase.DiffResult, in which case the primal value f(input) (or f(input...), if isa(input,
  Tuple)) will be stored in it as well.
```

I've added an example [here](https://github.com/JuliaDiff/ReverseDiff.jl/blob/master/examples/gradient.jl#L33).

**Comment by scidom** [comment]
Thanks @jrevels, I will have a closer look at the example and at DiffBase.jl, and will let you know if I need more help.

**Comment by scidom** [comment]
I have a follow up question. Here is a simple example, which shows how ``DiffBase.DiffResult`` share a unified interface in ForwardDiff and ReverseDiff:

```
using DiffBase, ForwardDiff, ReverseDiff

f(x) = sum(sin, x)+prod(tan, x)*sum(sqrt, x);

x = rand(4);

fresult = DiffBase.HessianResult(x);
rresult = DiffBase.HessianResult(x);

ForwardDiff.hessian!(fresult, f, x);

ReverseDiff.hessian!(rresult, f, x);

DiffBase.value(fresult)
DiffBase.value(rresult)

DiffBase.gradient(fresult)
DiffBase.gradient(rresult)

DiffBase.hessian(fresult)
DiffBase.hessian(rresult)
```

My question is whether the call `ReverseDiff.hessian!(rresult, f, x);` is indeed wasteful. More specifically, if I am going to make this call repeatedly, should I be using an `f_tape` instead? If my suspicion is correct, may I ask for some help to see how I can instantiate `GradientTape` in this example?

**Comment by jrevels** [comment]
This is covered in [ReverseDiff's documentation](http://www.juliadiff.org/ReverseDiff.jl/), specifically the `hessian!` and `HessianTape` sections.
