### ISSUE TITLE
Bad interaction with StaticArrays broadcast

### ISSUE THREAD

**Issue by tkoolen** [JuliaDiff/ReverseDiff.jl#64]
I was trying out using ReverseDiff with my package, which relies heavily on StaticArrays. Unfortunately, I ran into an issue with `broadcast`:
```julia
using ReverseDiff: GradientTape
using StaticArrays

function f(x)
    T = eltype(x)
    v = SVector(one(T), zero(T))
    sum(sum(x) * v)
end
f_tape = GradientTape(f, rand(1))
```
results in the following ambiguity error on 0.6 with StaticArrays 0.0.4 and ReverseDiff 0.1.2:
```
ERROR: MethodError: broadcast(::Base.#*, ::ReverseDiff.TrackedReal{Float64,Float64,Void}, ::StaticArrays.SVector{2,ReverseDiff.TrackedReal{Float64,Float64,ReverseDiff.TrackedArray{Float64,Float64,1,Array{Float64,1},Array{Float64,1}}}}) is ambiguous. Candidates:
  broadcast(f, a::Union{Number, StaticArrays.StaticArray}...) in StaticArrays at /home/twan/code/RigidBodyDynamics/v0.6/StaticArrays/src/broadcast.jl:8
  broadcast(::Base.#*, x::ReverseDiff.TrackedReal{X,D,O} where O, y::AbstractArray{T,1} where T) where {X, D} in ReverseDiff at /home/twan/code/RigidBodyDynamics/v0.6/ReverseDiff/src/derivatives/elementwise.jl:344
Stacktrace:
 [1] f(::ReverseDiff.TrackedArray{Float64,Float64,1,Array{Float64,1},Array{Float64,1}}) at ./REPL[7]:4
 [2] Type at /home/twan/code/RigidBodyDynamics/v0.6/ReverseDiff/src/api/tape.jl:176 [inlined]
 [3] ReverseDiff.GradientTape(::Function, ::Array{Float64,1}) at /home/twan/code/RigidBodyDynamics/v0.6/ReverseDiff/src/api/tape.jl:175
```

The relevant methods are:
* https://github.com/JuliaArrays/StaticArrays.jl/blob/v0.4.0/src/broadcast.jl#L8
* https://github.com/JuliaDiff/ReverseDiff.jl/blob/v0.1.2/src/derivatives/elementwise.jl#L344

How do you think this should be resolved?

**Comment by jrevels** [comment]
Ah, that's pretty painful.  Naively, I guess the easiest solution is to add StaticArrays types [here](https://github.com/JuliaDiff/ReverseDiff.jl/blob/master/src/ReverseDiff.jl#L23).

I think StaticArrays is probably popular enough at this point that JuliaDiff should have a "StaticArraysDiff" package (or whatever) that provides a bunch of StaticArrays-specialized ForwardDiff/ReverseDiff methods. See also https://github.com/JuliaDiff/ForwardDiff.jl/issues/208#issuecomment-288126127.

Even beyond StaticArrays, though, I imagine it would be pretty common for external array types to introduce ambiguities w.r.t. ReverseDiff methods. We should come up with a convenient process by which users can dynamically perform the equivalent of adding such array types to the aforementioned list and generating new methods.

It seems to me like this kind of compatibility problem would arise any time somebody tries to compose two sufficiently complex/specialized non-Base array types. I wonder how (or if) other folks have resolved it...might make a good post for Discourse.

**Comment by tkoolen** [comment]
Thanks for the quick response and workaround. I'll post on Discourse first, but first I'll play around with ReverseDiff a little more.

**Comment by tkoolen** [comment]
Just got back to this after working on some other stuff. I realize now that the bigger problem with StaticArrays and ReverseDiff is that `StaticArray`s are immutable, while ReverseDiff I guess expects non-input arrays used in the function to be mutable, correct? The ambiguity issues are still valid, but since you can't actually use StaticArrays with ReverseDiff anyway, I'll close this issue.
