### ISSUE TITLE
ForwardDiff limit

### ISSUE THREAD

**Issue by pkofod** [JuliaDiff/ReverseDiff.jl#72]
Is there a reason for the 0.5.0 upper limit and could it be lifted? Julia is going to go to v0.6 soon, and currently, the upper limit can cause conflicts between packages such as Optim, NLsolve, ForwardDiff and ReverseDiff.

**Comment by jrevels** [comment]
It'll require a bit of work to get ReverseDiff running properly with ForwardDiff 0.5, mainly rewriting scalar ops to respect the tagging system.

The plan is for the next big release of ReverseDiff (supporting/using ForwardDiff v0.5) to be built on top of https://github.com/jrevels/Cassette.jl, which is my WIP library that generalizes ReverseDiff's taping approach for non-differentiation use cases. In the meantime, I unfortunately don't have the bandwidth to do much maintenance on the existing ReverseDiff version.

**Comment by pkofod** [comment]
Alrighty, thanks for the reply!

**Comment by ChrisRackauckas** [comment]
Can ReverseDiff.jl be easily upgraded by making all of the tags `nothing`?

**Comment by jrevels** [comment]
> Can ReverseDiff.jl be easily upgraded by making all of the tags nothing?

Close. If I had the bandwidth to do this, I'd define a singleton `struct RDTag end` and then use the instance of that as the tag.

**Comment by ChrisRackauckas** [comment]
In that case, you can just tag everything with `:RDTag` right?

**Comment by jrevels** [comment]
> In that case, you can just tag everything with :RDTag right?

No. Having a singleton namespaced by ReverseDiff is more secure than picking a value in a type domain exposed by Base.

**Comment by jebej** [comment]
Is there any progress on this? ReverseDiff now causes a lot of packages to be held back:

```
julia> Pkg.add("ReverseDiff")                                                                   
INFO: Cloning cache of FunctionWrappers from https://github.com/yuyichao/FunctionWrappers.jl.git
INFO: Cloning cache of ReverseDiff from https://github.com/JuliaDiff/ReverseDiff.jl.git         
INFO: Downgrading DiffBase: v0.3.2 => v0.2.0                                                    
INFO: Downgrading DiffEqBase: v1.23.1 => v1.14.1                                                
INFO: Downgrading ForwardDiff: v0.6.0 => v0.4.2                                                 
INFO: Installing FunctionWrappers v0.1.0                                                        
INFO: Installing Iterators v0.3.1                                                               
INFO: Downgrading LineSearches: v2.2.1 => v0.1.5                                                
INFO: Downgrading NLsolve: v0.11.0 => v0.9.1                                                    
INFO: Downgrading Optim: v0.9.3 => v0.7.8                                                       
INFO: Downgrading OrdinaryDiffEq: v2.19.1 => v2.4.0                                             
INFO: Installing ReverseDiff v0.1.5                                                             
INFO: Removing CommonSubexpressions v0.0.1                                                      
INFO: Removing DiffEqDiffTools v0.0.2                                                           
INFO: Removing DiffResults v0.0.1                                                               
INFO: Removing DiffRules v0.0.1                                                                 
INFO: Removing MuladdMacro v0.0.2                                                               
INFO: Building SpecialFunctions                                                                 
INFO: Package database updated                                                                  
```

**Comment by jrevels** [comment]
see #94

**Comment by jebej** [comment]
Thanks!
