### ISSUE TITLE
In-place assignment on strictly typed vectors does not report error

### ISSUE THREAD

**Issue by mcovalt** [JuliaDiff/ReverseDiff.jl#76]
If using an in-place assignment operator `.=` from a tracked vector into a typed vector, no error is reported and an incorrect answer is given. Consider the following:

```
using ReverseDiff

function test1(x)
    out = Vector{Float64}(length(x))
    out .= 3.0.*x
    out .^= 2
    return sqrt(dot(out,out))
end
function test2(x)
    out = Vector{Any}(length(x))
    out .= 3.0.*x
    out .^= 2
    return sqrt(dot(out,out))
end

input = rand(3)
test1(input) == test2(input)
g1 = ReverseDiff.gradient(test1, input)
g2 = ReverseDiff.gradient(test2, input)
```

Output in Julia 0.5:
```
julia> test1(input) == test2(input)
    true
julia> g1 = ReverseDiff.gradient(test1, input)
    3-element Array{Float64,1}:
    0.0
    0.0
    0.0
julia> g2 = ReverseDiff.gradient(test2, input)
    3-element Array{Float64,1}:
    0.0936007
    6.53833
    13.5873
```

**Comment by jrevels** [comment]
This is due to https://github.com/JuliaDiff/ReverseDiff.jl/blob/d41a29f7d2bf8b1a5b6955f654f4fe5f34f61cca/src/tracked.jl#L246, which I knew about when adding it. I think I needed that method to support some other behavior, but I can't for the life of me remember what...

**Comment by antoine-levitt** [comment]
Just got hit by this, could this yield an error while the behavior is being worked out?
