### ISSUE TITLE
Where is the InstructionTape computed?

### ISSUE THREAD

**Issue by schlichtanders** [JuliaDiff/ReverseDiff.jl#96]
Dear author of ReverseDiff,

I am struggling understanding your code. You build a Tape and then compile it, but looking at your code, I so far am unable to spot where the concrete execution programm gets recorded, also called InstructionTape if I understood it correctly.

The nearest I could find is the creation of the JacobianTape for instance
https://github.com/JuliaDiff/ReverseDiff.jl/blob/820690c8efde8e71e1a7868949f7e703de144e03/src/api/tape.jl#L227-L231

out of a sudden, the InstructionTape is there, seemingly computed as a side-effect of running `f(cfg.input`. If this is really so, where is the computation of the side effect done in fact?

any code/documentation pointer or explanation is highly appriciated!
thank you a lot for this lovely package!

**Comment by jrevels** [comment]
> out of a sudden, the InstructionTape is there, seemingly computed as a side-effect of running f(cfg.input. If this is really so, where is the computation of the side effect done in fact?

That's exactly right! Instructions are pushed to the tape during program execution. This is done via overloading differentiable operations to work ReverseDiff's special scalar and array types. These operations are "intercepted" at run time, and then a record of the operation (inputs, outputs, function, and auxiliary data stored in a cache) is written to the tape.

The relevant method overloads can be found in the [src/derivatives](https://github.com/JuliaDiff/ReverseDiff.jl/tree/master/src/derivatives) folder.

**Comment by schlichtanders** [comment]
Thank you very much for the explanation and the pointer
lovely
